name = "amz2" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "api.instagram.com.amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "m.pubgmobile.com.amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "help.viu.com.amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "static-web.prod.vidiocdn.com.amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "app.genflix.co.id.amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "df.game.naver.com.amz2.noyszid.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "teams.live.com.amz2.noyszid.filegear-sg.me"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "c2cadcfe-d79b-4947-b451-29505cae9083"
