name = "DONASI" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern ="xyoru.xyz"
custom_domain = true
[[routes]]
pattern ="ava.game.naver.com.xyoru.xyz"
custom_domain = true
[[routes]]
pattern ="support.zoom.us.xyoru.xyz"
custom_domain = true
[[routes]]
pattern ="zoomgov.socifiles.com.xyoru.xyz"
custom_domain = true
[[routes]]
pattern ="cvc-deo.shopeemobile.com.xyoru.xyz"
custom_domain = true
[[routes]]
pattern ="m.instagram.com.xyoru.xyz"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "6de87889-e90b-4c4f-b66b-da476411e9f6"
