name = "ider" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "ider.1lunatic1icepick.my.id"
[[routes]]
pattern = "shopee.co.id.ider.1lunatic1icepick.my.id"
[[routes]]
pattern = "cf.shopee.co.id.ider.1lunatic1icepick.my.id"
[[routes]]
pattern = "cvs-deo.shopeemobile.com.ider.1lunatic1icepick.my.id"

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "57b40cc5-5cd5-4189-ad44-f49da7e68d85"
