name = "alibaba-vidio" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "alivid.taikuda.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "img.email1.vidio.com.alivid.taikuda.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "img.email3.vidio.com.alivid.taikuda.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.alivid.taikuda.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.alivid.taikuda.filegear-sg.me"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "f1add693-6553-4805-b00f-36ff5677fbf4"
