name = "HK" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "teams.microsoft.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "meetings.googleapis.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "zoomcares.zoom.us.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "maps.gstatic.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "edge.skype.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "meet.google.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "teams.live.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "kh.google.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "learn.microsoft.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "classroom.google.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "mapsplatform.google.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "maps.googleapis.com.hk.reinzvpn.filegear-sg.me"
custom_domain = true



[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "e25d79ab-ce7f-4e58-a2e7-323243e73181"
