name = "cf-worker-ws"
main = "_worker.js"
compatibility_date = "2024-04-29"

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
UUID = "1b6c1745-992e-4aac-8685-266c090e50ea,89b64978-6244-4bf3-bf64-67ade4ce5c8f,d342d11e-d424-4583-b36e-524ab1f0afa4"


## Docs: https://developers.cloudflare.com/workers/configuration/environment-variables/
[env.dev]
workers_dev = true

[env.dev.vars]
UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"


[env.prod]
workers_dev = false
minify = true
## Docs: https://developers.cloudflare.com/workers/configuration/routing/
# routes = [{ pattern = "666.666666.xyz", custom_domain = true }]

[env.prod.vars]
UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
