name = "test-my"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "test-my.whxdev.love", custom_domain = true },
  { pattern = "ava.game.naver.com.test-my.whxdev.love", custom_domain = true },
  { pattern = "investors.spotify.com.test-my.whxdev.love", custom_domain = true },
  { pattern = "investor.fb.com.test-my.whxdev.love", custom_domain = true },
  { pattern = "graph.instagram.com.test-my.whxdev.love", custom_domain = true },
  { pattern = "cache.netflix.com.test-my.whxdev.love", custom_domain = true },
  { pattern = "quiz.int.vidio.com.test-my.whxdev.love", custom_domain = true },
  { pattern = "zaintest.vuclip.com.test-my.whxdev.love", custom_domain = true },
  { pattern = "blog.webex.com.test-my.whxdev.love", custom_domain = true },
  { pattern = "support.zoom.us.test-my.whxdev.love", custom_domain = true },
]
workers_dev = false
[vars]
UUID = "cf76a0ef-0b95-4e28-ab41-5faf69b60a6f"
DNS_RESOLVER_URL = "https://dns.cloudflare.com/dns-query"
