name = "ikd" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "*.fb.com.xr-atha001.vpnwild.xyz"
custom_domain = true
[[routes]]
pattern = "*.fb.com.tr-atha001.vpnwild.xyz"
custom_domain = true

[[routes]]
pattern = "*.ava.game.naver.com.xr-atha001.vpnwild.xyz"
custom_domain = true
[[routes]]
pattern = "*.ava.game.naver.com.tr-atha001.vpnwild.xyz"
custom_domain = true

[[routes]]
pattern = "*.webex.com.xr-atha001.vpnwild.xyz"
custom_domain = true
[[routes]]
pattern = "*.webex.com.tr-atha001.vpnwild.xyz"
custom_domain = true

[[routes]]
pattern = "*.zoom.us.xr-atha001.vpnwild.xyz"
custom_domain = true
[[routes]]
pattern = "*.zoom.us.tr-atha001.vpnwild.xyz"
custom_domain = true

[[routes]]
pattern = "*.noice.id.xr-atha001.vpnwild.xyz"
custom_domain = true
[[routes]]
pattern = "*.noice.id.tr-atha001.vpnwild.xyz"
custom_domain = true

[[routes]]
pattern = "*.spotify.com.xr-atha001.vpnwild.xyz"
custom_domain = true
[[routes]]
pattern = "*.spotify.com.tr-atha001.vpnwild.xyz"
custom_domain = true

[[routes]]
pattern = "*.vidio.com.xr-atha001.vpnwild.xyz"
custom_domain = true
[[routes]]
pattern = "*.vidio.com.tr-atha001.vpnwild.xyz"
custom_domain = true

[[routes]]
pattern = "*.ruangguru.com.xr-atha001.vpnwild.xyz"
custom_domain = true
[[routes]]
pattern = "*.ruangguru.com.tr-atha001.vpnwild.xyz"
custom_domain = true

[[routes]]
pattern = "*.duolingo.com.xr-atha001.vpnwild.xyz"
custom_domain = true
[[routes]]
pattern = "*.duolingo.com.tr-atha001.vpnwild.xyz"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "dc416f27-c604-5af0-9732-016e9e3814bb"
