name = "memek" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "indo.solovpn.cloud"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.indo.solovpn.cloud"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.indo.solovpn.cloud"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.indo.solovpn.cloud"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.indo.solovpn.cloud"
custom_domain = true
[[routes]]
pattern = "api.zoom.us.indo.solovpn.cloud"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "7ee8caf9-f1cf-4479-858e-f4fbdf4c8d48"
