name = "contoh" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern=
"nama domain 1"
custom-domain=true
[[routes]]
pattern=
"nama domain 2"
custom-domain=true
[[routes]]
pattern=
"nama domain 3"
custom-domain=true
[[routes]]
pattern=
"nama domain"
custom-domain=true


[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "b97e81a3-4c6f-4370-8500-8b010e335307"
