name = "jembut" # todo
#name = "cf-worker-connect-test" # todop
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "patunganvps.net"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.jembut.patunganvps.net"
custom_domain = true
[[routes]]
pattern = "df.game.naver.com.jembut.patunganvps.net"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.jembut.patunganvps.net"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.jembut.patunganvps.net"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "7266dbd9-b8d4-4c5f-9b42-9e36b44a4a41"
