name = "id1" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "id1.tingkehvpn.my.id"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.id1.tingkehvpn.my.id"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.id1.tingkehvpn.my.id"
custom_domain = true
[[routes]]
pattern = "v.whatsapp.com.id1.tingkehvpn.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.id1.tingkehvpn.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.id1.tingkehvpn.biz.id"
custom_domain = true
[[routes]]
pattern = "poe.garena.com.id1.tingkehvpn.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.id1.tingkehvpn.biz.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "f9021b31-e8bd-4b4d-a1d3-c9b0c1476c44"
