name = "envyous-ovh" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "ovh.envy-cakill.biz.id"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.ovh.envy-cakill.biz.id"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.ovh.envy-cakill.biz.id"
custom_domain = true
[[routes]]
pattern = "cv.shopee.sg.ovh.envy-cakill.biz.id"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.ovh.envy-cakill.biz.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "d4efe477-3a36-4294-ae80-783448fbde81"
