name = "sg11" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cv.shopee.sg.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "img.email3.vidio.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "edu.ruangguru.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "marketing.ruangguru.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "onelink.seabank.co.id.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cdn.i-joox.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "app.genflix.co.id.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "web.joox.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "dev-cdn.i-joox.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "support.duolingo.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "www.webex.com.sg11.kyrie.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "beta.zoom.us.sg11.kyrie.filegear-sg.me"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "77ee00b0-addc-4ea0-9e58-fe95d155969f"
