name = "sg-linode" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "xnxx.rezasenpai.xyz"
custom_domain = true
[[routes]]
pattern = "sb.scorecardresearch.com.xnxx.rezasenpai.xyz"
custom_domain = true
[[routes]]
pattern = "click.axis.co.id.xnxx.rezasenpai.xyz"
custom_domain = true
[[routes]]
pattern = "static-web.prod.vidiocdn.com.xnxx.rezasenpai.xyz"
custom_domain = true
[[routesl]]
pattern = "Nontontv.vidio.com.xnxx.rezasenpai.xyz"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "714779db-6714-4960-bf0b-6d483066dcbb"
